const dishes=[
 {name:'The Hippo Classic',category:'small',price:11,description:'Handcrafted beef, crisp lettuce, tomato, Hippo sauce',image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80'},
 {name:'Sriracha Burger',category:'small',price:13,description:'Spicy sriracha sauce, melted cheese, fresh crunch',image:'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80'},
 {name:'Bacon BBQ Stack',category:'small',price:14,description:'Crispy bacon, smoky BBQ, onion rings, cheddar',image:'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=800&q=80'},
 {name:'Crispy Chicken Combo',category:'fire',price:13,description:'Golden chicken, signature sauce, fries and a drink',image:'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80'},
 {name:'Loaded Hippo Fries',category:'fire',price:9,description:'Seasoned fries, cheese sauce, bacon and ranch',image:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80'},
 {name:'Cookies & Cream Shake',category:'sweet',price:7,description:'Thick, cold, creamy, and finished with cookie crumble',image:'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=800&q=80'}
];
let basket=[];const grid=document.querySelector('#menu-grid');
function renderMenu(category='all'){grid.innerHTML=dishes.filter(d=>category==='all'||d.category===category).map((d,i)=>`<article class="menu-card" style="animation-delay:${i*50}ms"><div class="menu-card-image" style="background-image:url('${d.image}')"></div><div class="menu-card-body"><div class="menu-card-top"><h3>${d.name}</h3><span class="price">$${d.price}</span></div><p>${d.description}</p><button class="add-btn" data-add="${d.name}">Add to basket +</button></div></article>`).join('');grid.querySelectorAll('[data-add]').forEach(btn=>btn.addEventListener('click',()=>{basket.push(dishes.find(d=>d.name===btn.dataset.add));renderBasket();document.querySelector('.cart-drawer').classList.add('open');document.querySelector('.drawer-backdrop').classList.add('open')}))}
function renderBasket(){document.querySelector('.cart-count').textContent=basket.length;const items=document.querySelector('.cart-items'),empty=document.querySelector('.cart-empty'),total=document.querySelector('.cart-total strong span');empty.style.display=basket.length?'none':'block';items.innerHTML=basket.map((d,i)=>`<div class="cart-item"><div><strong>${d.name}</strong><small>$${d.price}</small></div><button class="remove-item" data-remove="${i}">Remove</button></div>`).join('');items.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{basket.splice(+b.dataset.remove,1);renderBasket()}));total.textContent=basket.reduce((sum,d)=>sum+d.price,0)}
renderMenu();renderBasket();
document.querySelectorAll('.menu-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.menu-tabs .active').classList.remove('active');b.classList.add('active');renderMenu(b.dataset.category)}));
document.querySelector('[data-scroll-menu]').addEventListener('click',()=>document.querySelector('#menu').scrollIntoView());
document.querySelectorAll('[data-open-reservation]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#reservation-modal').classList.add('open');document.body.classList.add('no-scroll')}));
document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#reservation-modal').classList.remove('open');document.body.classList.remove('no-scroll')}));
document.querySelectorAll('[data-open-cart]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.cart-drawer').classList.add('open');document.querySelector('.drawer-backdrop').classList.add('open')}));
document.querySelectorAll('[data-close-cart]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.cart-drawer').classList.remove('open');document.querySelector('.drawer-backdrop').classList.remove('open')}));
document.querySelector('#reservation-form').addEventListener('submit',e=>{e.preventDefault();e.target.querySelector('.primary-btn').style.display='none';document.querySelector('.form-message').textContent='Great â€” we will hold your table while we confirm the details.'});
document.querySelector('[data-open-menu]').addEventListener('click',()=>document.querySelector('#menu').scrollIntoView());
document.querySelector('.checkout-btn').addEventListener('click',()=>alert('Demo checkout â€” connect your ordering provider here.'));

