const dishes=[
 {name:'Charred sourdough',category:'small',price:9,description:'Cultured butter, smoked salt, rooftop honey',image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80'},
 {name:'Crispy oysters',category:'small',price:18,description:'Meyer lemon, green chile, herb snow',image:'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80'},
 {name:'Ember-roasted carrots',category:'small',price:15,description:'Whipped feta, pistachio, burnt orange',image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80'},
 {name:'Whole branzino',category:'fire',price:34,description:'Preserved lemon, salsa verde, crispy potato',image:'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80'},
 {name:'Coal-roasted half chicken',category:'fire',price:29,description:'Green garlic jus, charred spring onion',image:'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80'},
 {name:'Olive oil cake',category:'sweet',price:12,description:'Citrus curd, sea salt, vanilla cream',image:'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80'}
];
let basket=[];const grid=document.querySelector('#menu-grid');
function renderMenu(category='all'){grid.innerHTML=dishes.filter(d=>category==='all'||d.category===category).map((d,i)=>`<article class="menu-card" style="animation-delay:${i*50}ms"><div class="menu-card-image" style="background-image:url('${d.image}')"></div><div class="menu-card-body"><div class="menu-card-top"><h3>${d.name}</h3><span class="price">$${d.price}</span></div><p>${d.description}</p><button class="add-btn" data-add="${d.name}">Add to basket +</button></div></article>`).join('');grid.querySelectorAll('[data-add]').forEach(btn=>btn.addEventListener('click',()=>{basket.push(dishes.find(d=>d.name===btn.dataset.add));renderBasket();document.querySelector('.cart-drawer').classList.add('open');document.querySelector('.drawer-backdrop').classList.add('open')}))}
function renderBasket(){document.querySelector('.cart-count').textContent=basket.length;const items=document.querySelector('.cart-items'),empty=document.querySelector('.cart-empty'),total=document.querySelector('.cart-total strong span');empty.style.display=basket.length?'none':'block';items.innerHTML=basket.map((d,i)=>`<div class="cart-item"><div><strong>${d.name}</strong><small>$${d.price}</small></div><button class="remove-item" data-remove="${i}">Remove</button></div>`).join('');items.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{basket.splice(+b.dataset.remove,1);renderBasket()}));total.textContent=basket.reduce((sum,d)=>sum+d.price,0)}
renderMenu();renderBasket();
document.querySelectorAll('.menu-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.menu-tabs .active').classList.remove('active');b.classList.add('active');renderMenu(b.dataset.category)}));
document.querySelector('[data-scroll-menu]').addEventListener('click',()=>document.querySelector('#menu').scrollIntoView());
document.querySelectorAll('[data-open-reservation]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#reservation-modal').classList.add('open');document.body.classList.add('no-scroll')}));
document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#reservation-modal').classList.remove('open');document.body.classList.remove('no-scroll')}));
document.querySelectorAll('[data-open-cart]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.cart-drawer').classList.add('open');document.querySelector('.drawer-backdrop').classList.add('open')}));
document.querySelectorAll('[data-close-cart]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.cart-drawer').classList.remove('open');document.querySelector('.drawer-backdrop').classList.remove('open')}));
document.querySelector('#reservation-form').addEventListener('submit',e=>{e.preventDefault();e.target.querySelector('.primary-btn').style.display='none';document.querySelector('.form-message').textContent='Great â€” we will hold your table while we confirm the details.'});
document.querySelector('[data-open-menu]').addEventListener('click',()=>document.querySelector('#menu').scrollIntoView());
document.querySelector('.checkout-btn').addEventListener('click',()=>alert('Demo checkout â€” connect your ordering provider here.'));

